export const SET_ALERT = "SET_ALERT";
export const RESET_ALERT = "RESET_ALERT";

export const POST_DATA = "POST_DATA";
export const POSTED_DATA = "POSTED_DATA";

export const SET_LOADING = "SET_LOADING";
export const SET_API_DATA = "SET_API_DATA";
export const API_ERROR = "API_ERROR";
export const SET_PRODUCT_DETAILS_LOADING = "SET_PRODUCT_DETAILS_LOADING";
export const SET_PRODUCT_DETAILS = "SET_PRODUCT_DETAILS";
export const SET_PRODUCT_DETAILS_ERROR = "SET_PRODUCT_DETAILS_ERROR";

export const SET_GRID_VIEW = "SET_GRID_VIEW";
export const SET_LIST_VIEW = "SET_LIST_VIEW";
export const GET_SORT_VALUE = "GET_SORT_VALUE";
export const UPDATE_FILTERS_VALUE = "UPDATE_FILTERS_VALUE";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const SORTING_PRODUCTS = "SORTING_PRODUCTS";
export const LOAD_FILTER_PRODUCTS = "LOAD_FILTER_PRODUCTS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CLEAR_CART = "CLEAR_CART";
export const SET_DECREMENT = "SET_DECREMENT";
export const SET_INCREMENT = "SET_INCREMENT";
export const CART_TOTAL_ITEM = "CART_TOTAL_ITEM";
export const CART_TOTAL_PRICE = "CART_TOTAL_PRICE";
